services:
  django:
    image: sakhi2000/attendance-service
    container_name: attendance-service
    build:
      context: webapi/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - bot
  bot:
    image: sakhi2000/attendance-bot-service
    container_name: attendance-bot-service
    build:
      context: bot/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./logs:/home/logs

  db:
      image: postgres
      container_name: attendance-service-db
      ports:
        - 5489:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_NAME: postgres
      volumes:
        - attendance-data:/var/lib/postgresql/data

volumes:
  attendance-data:
